
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [8]:
import numpy as np 
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [11]:
array = np.arange(1,10)
array
reshaped_array = array.reshape((3,3))
reshaped_array


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Access the element at the second row, second column.


In [12]:
reshaped_array[1,1]

5

Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [38]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array1 + array2
array2 - array1
array1 * array2

array([ 4, 10, 18])

Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [19]:
array = np.array([1,2,3,4])
array_sum = array.sum()
array_mean = array.mean()
array_std = array.std()
print(array_sum,array_mean,array_std)


10 2.5 1.118033988749895


Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [21]:
array = np.arange(6)
array
reshaped_array = array.reshape((2,3))
reshaped_array


array([[0, 1, 2],
       [3, 4, 5]])


# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [24]:
random_array = np.random.randint(50,100, size = (5,5))
random_array

array([[99, 96, 53, 80, 91],
       [87, 89, 61, 55, 86],
       [91, 89, 87, 59, 93],
       [82, 52, 85, 61, 94],
       [62, 72, 67, 98, 65]])

Replace all values in the sub-array with a specific value.


In [28]:
random_array[1:4,:] = 8
random_array   

array([[10, 10, 10, 10, 10],
       [ 8,  8,  8,  8,  8],
       [ 8,  8,  8,  8,  8],
       [ 8,  8,  8,  8,  8],
       [10, 10, 10, 10, 10]])

Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [32]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
arr
arr[[1,3],:]

array([[3, 4],
       [7, 8]])


# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [37]:
array = np.array([0,1,2])
array

array_2d = np.tile(array ,(3,1))

print(array_2d)


[[0 1 2]
 [0 1 2]
 [0 1 2]]


Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [39]:
array_1d = np.array([0,1,2])
array_1d +

array([0, 1, 2])

# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [48]:
random_array1 = np.random.randint(1,100, size = (3,3))
random_array1
random_array2 = np.random.randint(1,100, size = (3,3))
random_array2
Concatenate_horizonatally= np.hstack((random_array1,random_array2))
Concatenate_horizonatally


array([[23, 82, 54, 63, 85, 31],
       [64, 69, 83, 63, 31, 33],
       [ 6, 68, 98, 35, 16,  3]])

In [47]:
Concatenate_vertically= np.vstack((random_array1,random_array2))
Concatenate_vertically


array([[93,  4, 92],
       [72, 88, 26],
       [98, 89, 81],
       [77, 74, 49],
       [77, 41, 78],
       [40,  4, 69]])

In [56]:
splitted_array = np.hsplit(Concatenate_horizonatally,2)
splitted_array


[array([[23, 82, 54],
        [64, 69, 83],
        [ 6, 68, 98]]),
 array([[63, 85, 31],
        [63, 31, 33],
        [35, 16,  3]])]

In [57]:
splitted_array_ver = np.vsplit(Concatenate_vertically,2)
splitted_array_ver

[array([[93,  4, 92],
        [72, 88, 26],
        [98, 89, 81]]),
 array([[77, 74, 49],
        [77, 41, 78],
        [40,  4, 69]])]

# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [58]:
array = np.array([1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5])
count_dict ={}
for i in array:
    if i in count_dict:
        count_dict[i]=+1
    else i in count_dict:
        count_dict[i]=1
        
        

SyntaxError: expected ':' (4111865945.py, line 6)

# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

